name: Actions Workflow
# on: [push, pull_request]
on:
  push:
    branches:
      - "main"
      - "feature/*" # matches featur/featA, feature/featB, doesn't match feature/feat/a
      # - "feature/**" # matches featur/featA, feature/featB, match feature/feat/a
      - "!feature/vaiCuc"

    # Example: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    # branches-ignore:
    #   - null
    # tags:
    #   - "latest"
    # tags-ignore:
    #   - null
    # paths:
    #   - "**.js"
    #   - "!filename.js"
    # paths-ignore:
    #   - null

  # repository_dispatch:
  #   types: [build]

  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *" 

  # push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload check
        run: echo ${{ github.event.client_payload.env }}
      - name: List files
        run: | 
          ls -a
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Action checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        run: | 
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
