name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:17.9.0-alpine
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:18.5-alpine3.15
        with:
          entrypoint: "/bin/echo"
          args: "Hello World!"

      - name: Step with docker
        uses: docker://node:18.5-alpine3.15
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses:  actions/checkout@v1
      - name: Run a script
        uses: docker://node:18.5-alpine3.15
        with:
          entrypoint: ./script.sh
          args: -v -c hehe
          
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: ducpp/node-api
        ports:
          - 3000:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: |
          curl --location --request POST 'http://localhost:3000/api/user' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "username" : "no one",
              "address" : "no where"
          }'
      - name: Get Users
        run: |
          curl --location --request GET 'http://localhost:3000/api/users'




  # node-docker:
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: node:lts-alpine
  #     # volumes:
  #     # options: 
  #   steps:
  #     - name: Log node version
  #       run: |
  #         node -v
  #         [[ -f "/etc/os-release" ]] && cat /etc/os-release
          

