name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - name: Log node version
        run: node -v